  name:Github Action WorkFlows
  on:
    push:
      branches: [ "*" ]
    pull_request:
      branches: [ "*" ]
      paths-ignore:
        - '*.md'
        - '*.yml'
        - 'docs/**'

  jobs:
    build-binaries:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: true

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: Build aiges
          run: |
            make dist
        
          



