name: Github Action WorkFlows
on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '*.yml'
      - 'docs/**'

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    # 项目构建
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build aiges
        run: |
          make clean
          make build-pack
    # 构建镜像到docker hub

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2             
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}     
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: seawyq/cuda-go-python-base    
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./docker/gpu/base/cuda-10.1/Dockerfile
    # 构建镜像到AWS
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      - name: Get repo name
        id: repoName
        run: echo "::set-output name=reponame::$(echo ${{github.repository}} | cut -d '/' -f 2)"

      - name: Build and Push to ECR public
        id: build-and-push
        uses: pahud/ecr-public-action@0db8adbcfd3c3ec2f604d70fdd6b5d15c80e1dbc
        with:
          dockerfile: ./docker/gpu/base/cuda-10.1/Dockerfile
          context: .
          create_repo: ${{ steps.repoName.outputs.reponame }}
          tags: |
            public.ecr.aws/iflytek-open/${{ steps.repoName.outputs.reponame }}:latest