name: Github Action WorkFlows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '*.yml'
      - 'docs/**'

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build aiges
        run: |
          make clean
          make
          make pack

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/aiservice.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

          



