name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.18

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}

      - name: Note
        id: Note
        env:
          VERSION: ${{ steps.prepare.outputs.tag_name }}
        run: |
          cd hack/release && sh note.sh

      - name: Release
        run: |
          export GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
          make build-release
